app01/models.py
from django.db import models


# Create your models here.


class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name="Username", max_length=32)
    password = models.CharField(verbose_name="Password", max_length=64)

    def __str__(self):
        return self.username


class Menu(models.Model):
    """ all meun """
    name = models.CharField(verbose_name="Name", max_length=32)
    time = models.IntegerField(verbose_name="time need to be done")

    tem = models.IntegerField(verbose_name="temperature")
    inter = models.CharField(verbose_name="materials needed", max_length=256)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/')


class meat(models.Model):
    """ The ingredients """
    meat = models.CharField(verbose_name="Meat", max_length=16, default="Beef")
    quantity = models.IntegerField(default=1, verbose_name="Amount")

    def __str__(self):
        return self.meat


class Auxiliary(models.Model):
    """ The ingredients """
    aux = models.CharField(verbose_name="aux", max_length=16, default="Salt")

    quantity = models.IntegerField(default=1, verbose_name="Amount")

    def __str__(self):
        return self.aux


class vegetable(models.Model):
    """ The ingredients """
    veg = models.CharField(verbose_name="vegetable", max_length=16, default="coriander")
    quantity = models.IntegerField(default=1, verbose_name="Amount")

    def __str__(self):
        return self.veg


class home(models.Model):
    """ The data in home page"""

    name = models.CharField(verbose_name="Name", max_length=64)
    temperature = models.IntegerField(verbose_name="Temperature", default=0)
    time = models.IntegerField(verbose_name="Time")
    utensils = models.CharField(verbose_name="Utensils", max_length=128)
    cate_food = (
        (1, "Most popular"),
        (2, "Best taste"),
        (3, "Vegetarianism"),
        (4, "Gorgeous"),
        (5, "Fast speed"),
        (6, "Breakfast"),
        (7, "Homely recipes"),
        (8, "Baking"),
        (9, "Children's food"),
        (10, "Baking"),
        (11, "Stape Food"),
        (12, "Dessert"),
        (13, "Snack"),
        (14, "Western Food"),
    )
    cate = models.SmallIntegerField(verbose_name="Category", choices=cate_food, default=1)
    description = models.TextField(verbose_name="Description", max_length=256, default="Delicious")
    meat = models.ForeignKey('meat', models.CASCADE)
    auxiliary = models.ForeignKey('Auxiliary', models.CASCADE)
    veg = models.ForeignKey('vegetable', models.CASCADE)
    quan = models.IntegerField(verbose_name="Amount", default=1)

    steps = models.TextField(verbose_name="Steps", max_length=500)
    Rate_stars = (
        (1, "One star"),
        (2, "Two stars"),
        (3, "Three stars"),
        (4, "Four stars"),
        (5, "Five stars"),
    )
    rate = models.IntegerField(verbose_name="Rate", choices=Rate_stars, default=3)
    calories = models.DecimalField(verbose_name="Calories", max_digits=6, decimal_places=2, default=300)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/', default='Menu/10.jpeg')


class favorite(models.Model):
    """ The data in home page """
    name = models.CharField(verbose_name="Name", max_length=64)
    temperature = models.IntegerField(verbose_name="Temperature", default=0)
    time = models.IntegerField(verbose_name="Time")
    utensils = models.CharField(verbose_name="Utensils", max_length=128)
    cate_food = (
        (1, "Most popular"),
        (2, "Best taste"),
        (3, "Vegetarianism"),
        (4, "Gorgeous"),
        (5, "Fast speed"),
        (6, "Breakfast"),
        (7, "Homely recipes"),
        (8, "Baking"),
        (9, "Children's food"),
        (10, "Baking"),
        (11, "Stape Food"),
        (12, "Dessert"),
        (13, "Snack"),
        (14, "Western Food"),
    )
    cate = models.SmallIntegerField(verbose_name="Category", choices=cate_food, default=1)
    description = models.TextField(verbose_name="Description", max_length=256, default="Delicious")
    meat = models.ForeignKey('meat', models.CASCADE)
    auxiliary = models.ForeignKey('Auxiliary', models.CASCADE)
    veg = models.ForeignKey('vegetable', models.CASCADE)
    quan = models.IntegerField(verbose_name="Amount", default=1)

    steps = models.TextField(verbose_name="Steps", max_length=500)
    Rate_stars = (
        (1, "One star"),
        (2, "Two stars"),
        (3, "Three stars"),
        (4, "Four stars"),
        (5, "Five stars"),
    )
    rate = models.IntegerField(verbose_name="Rate", choices=Rate_stars, default=3)
    calories = models.DecimalField(verbose_name="Calories", max_digits=6, decimal_places=2, default=300)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/', default='Menu/10.jpeg')


class cust_recipe(models.Model):
    """ The user create their own recipes """
    name = models.CharField(verbose_name="Name", max_length=64)
    temperature = models.IntegerField(verbose_name="Temperature", default=0)
    time = models.IntegerField(verbose_name="Time")
    utensils = models.CharField(verbose_name="Utensils", max_length=128)
    cate_food = (
        (1, "Most popular"),
        (2, "Best taste"),
        (3, "Vegetarianism"),
        (4, "Gorgeous"),
        (5, "Fast speed"),
        (6, "Breakfast"),
        (7, "Homely recipes"),
        (8, "Baking"),
        (9, "Children's food"),
        (10, "Baking"),
        (11, "Stape Food"),
        (12, "Dessert"),
        (13, "Snack"),
        (14, "Western Food"),
    )
    cate = models.SmallIntegerField(verbose_name="Category", choices=cate_food, default=1)
    description = models.TextField(verbose_name="Description", max_length=256, default="Delicious")
    meat = models.ForeignKey('meat', models.CASCADE)
    auxiliary = models.ForeignKey('Auxiliary', models.CASCADE)
    veg = models.ForeignKey('vegetable', models.CASCADE)
    quan = models.IntegerField(verbose_name="Amount", default=1)

    steps = models.TextField(verbose_name="Steps", max_length=500)
    Rate_stars = (
        (1, "One star"),
        (2, "Two stars"),
        (3, "Three stars"),
        (4, "Four stars"),
        (5, "Five stars"),
    )
    rate = models.IntegerField(verbose_name="Rate", choices=Rate_stars, default=3)
    calories = models.DecimalField(verbose_name="Calories", max_digits=6, decimal_places=2, default=300)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/', default='Menu/10.jpeg')

app01/views/category.py
from django.shortcuts import render
from app01 import models


def page(request):
    queryset = models.home.objects.all()
    return render(request, 'category.html', {"queryset": queryset})

app01/views/mail.py
from django.shortcuts import HttpResponse
from django.core.mail import send_mail


def sendmail(request):
    """ send email """
    send_mail(subject='This is for practice',
              message='Hi, I am testing if the codes work！',
              from_email='jingyumengdcy@126.com',  # The sender's email
              # recipient_list=['Yu.Meng.Jing@ibm.com'],  # The receiver's email
              recipient_list=['h3c273wechat@gamil.com'],  # The receiver's email
              fail_silently=False)

    return HttpResponse("Send successfully!")

app01/views/main.py
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination
from django import forms
from django.shortcuts import render, redirect
from app01 import models


class MainMenuModelForm(BootStrapModelForm):
    class Meta:
        model = models.home
        fields = "__all__"
        # exclude = ["id"]


class MainMenuModelForm1(BootStrapModelForm):
    class Meta:
        model = models.cust_recipe
        fields = "__all__"
        # exclude = ["id"]


# Main menu
def home(request):
    # # Search function

    search_data = request.GET.get('q', "")

    queryset = models.home.objects.filter(name__icontains=search_data)
    if queryset:
        page_object = Pagination(request, queryset)
        context = {
            "search_data": search_data,
            "queryset": page_object.page_queryset,
            "page_string": page_object.html(),
        }
        return render(request, 'main.html', context)

    queryset = models.home.objects.filter(calories__icontains=search_data)

    page_object = Pagination(request, queryset)
    context = {
        "search_data": search_data,
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
    }
    return render(request, 'main.html', context)


def home1(request):
    # # Search function

    search_data = request.GET.get('q', "")

    queryset = models.cust_recipe.objects.filter(name__icontains=search_data)
    if queryset:
        page_object = Pagination(request, queryset)
        context = {
            "search_data": search_data,
            "queryset": page_object.page_queryset,
            "page_string": page_object.html(),
        }
        return render(request, 'main1.html', context)

    queryset = models.cust_recipe.objects.filter(calories__icontains=search_data)

    page_object = Pagination(request, queryset)
    context = {
        "search_data": search_data,
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
    }
    return render(request, 'main1.html', context)


def main_menu_add(request):
    """ Add the menu in main page """
    title = "Create your new menu"
    if request.method == 'GET':
        form = MainMenuModelForm()

        return render(request, 'upload_form.html', {"form": form, "title": title})
    form = MainMenuModelForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/main/')
    return render(request, 'upload_form.html', {"form": form, "title": title})


def main_menu_add1(request):
    """ Add the menu in main page for customer """
    title = "Create your new menu(customize)"
    if request.method == 'GET':
        form = MainMenuModelForm1()

        return render(request, 'upload_form.html', {"form": form, "title": title})
    form = MainMenuModelForm1(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/main1/')
    return render(request, 'upload_form.html', {"form": form, "title": title})


# Second menu
class MenuModelForm(BootStrapModelForm):
    class Meta:
        model = models.Menu
        fields = "__all__"
        # exclude = ["id"]


def add_meun(request):
    title = "Create menu"
    if request.method == 'GET':
        form = MenuModelForm()

        return render(request, 'upload_form.html', {"form": form, "title": title})
    form = MenuModelForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/meun/list/')
    return render(request, 'upload_form.html', {"form": form, "title": title})


def edit_meun(request, nid):
    """ Edit """
    if request.method == 'GET':
        row_object = models.Menu.objects.filter(id=nid).first()
        form = MenuModelForm(instance=row_object)
        return render(request, 'meun_edit.html', {"form": form})

    row_object = models.Menu.objects.filter(id=nid).first()

    form = MenuModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/meun/list/')
    return render(request, 'meun_edit.html', {"form": form})


def delete_meun(request, nid):
    models.home.objects.filter(id=nid).delete()
    return redirect('/meun/list/')

app01/views/subpage1.py
from app01.utils.pagination import Pagination
from openpyxl import load_workbook
from django.shortcuts import render, redirect, HttpResponse
from app01 import models
from django.views.decorators.csrf import csrf_exempt


def page(request):
    """ Most popular """

    queryset = models.home.objects.filter(cate=1)

    return render(request, 'subpage1.html', {"queryset": queryset})


def page2(request):
    """ Best taste """
    queryset = models.home.objects.filter(cate=2)
    return render(request, 'subpage1.html', {"queryset": queryset})


def page3(request):
    """ VEGETARIANISM"""
    queryset = models.home.objects.filter(cate=3)
    return render(request, 'subpage1.html', {"queryset": queryset})


def page4(request):
    """ Gorgeous """
    queryset = models.home.objects.filter(cate=4)
    return render(request, 'subpage1.html', {"queryset": queryset})


def page5(request):
    """ Fast Food """
    queryset = models.home.objects.filter(cate=5)
    return render(request, 'subpage1.html', {"queryset": queryset})


def page6(request):
    """ Breakfast """
    queryset = models.home.objects.filter(cate=6)
    return render(request, 'subpage1.html', {"queryset": queryset})


def page7(request):
    """ Homely recipes """
    queryset = models.home.objects.filter(cate=7)
    return render(request, 'subpage1.html', {"queryset": queryset})


def page8(request):
    """ Baking """
    queryset = models.home.objects.filter(cate=8)
    return render(request, 'subpage1.html', {"queryset": queryset})


def page9(request):
    """ Child's food"""
    queryset = models.home.objects.filter(cate=9)
    return render(request, 'subpage1.html', {"queryset": queryset})

def page10(request):
    """ Recommand """
    queryset = models.home.objects.filter(cate=9)
    return render(request, 'subpage1.html', {"queryset": queryset})

def page11(request):
    """ Staple food"""
    queryset = models.home.objects.filter(cate=11)
    return render(request, 'subpage1.html', {"queryset": queryset})


def page12(request):
    """ Dessert food"""
    queryset = models.home.objects.filter(cate=12)
    return render(request, 'subpage1.html', {"queryset": queryset})


def page13(request):
    """ Snack food"""
    queryset = models.home.objects.filter(cate=13)
    return render(request, 'subpage1.html', {"queryset": queryset})


def page14(request):
    """ Western food"""
    queryset = models.home.objects.filter(cate=14)
    return render(request, 'subpage1.html', {"queryset": queryset})

app01/templates/category.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
        .one {
            width: 100%;
            height: 400px;
            margin: 50px 0 30px 0;
            background-color: lightblue;

        }

        .two {
            float: left;
            width: 200px;
            height: 100%;

        }

        .two h2 {
            text-align: center;
            margin-top: 150px;
        }


        .three ul {
            width: 804px;
            float: right;
            background: #fff;
            margin-bottom: -1px;
        }


        ol, ul {
            list-style: none;
        }

        * {
            margin: 0;
            padding: 0;
        }

        .three {
            margin-left: 1px;
            float: left;
        }

        .three a {
            float: left;
            height: 132px;
            line-height: 64px;
            width: 265px;
            border-left: 1px solid #eeeeee;
            border-bottom: 1px solid #eeeeee;
            font-size: 20px;
            color: #333;
            text-decoration: none;
            text-align: center;
            position: relative;
        }


	</style>


	<div class="container">
		<div class="one">
			<div class="two">
				<h2>Meat class</h2>

			</div>
			<div class="three">
				<ul>
					{% for obj in queryset %}
						<li><a title="Meat" href="#" target="_blank">{{ obj.get_cate_display }}  </a></li>

					{% endfor %}
				</ul>
			</div>
		</div>


	</div>



{% endblock %}

app01/templates/main.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
        .thumbnail {
            width: 100%;
            padding: 2px;
            margin-bottom: 20px;
            background-color: #e8e8e8;
            border: 18px solid honeydew;
            height: 530px;
        }

        .sub-header a {
            float: left;
            width: 100px;
            text-align: center;
            text-decoration: none;
            font-size: 14px;
        }

        .container .w {
            background-color: #fff;
        }

        .w {
            width: 1170px;
            height: 400px;
            margin-left: -15px;
        }


        .sub-header a img {
            width: 60px;
            height: 60px;

            margin: 0 auto 5px;
            border-radius: 50%;
        }


        .sub-header {
            margin-top: 20px;
            margin-left: 80px;
            width: 1170px;

        }

        .row {
            position: relative;
            padding-top: 15px;
            margin-left: 5px;
        }

        .item img {
            display: block;
            max-width: 100%;
            height: auto;
        }

        .carousel-inner {
            height: 200px;
            width: 1170px;
        }

        .four4 a {
            float: right;
        }

        .item1 img {
            width: 400px;
            height: 200px;
        }


        .caption {
            height: 150px;
        }

        .avatar {
            color: #fff;
            background-color: #adb5bd;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            font-size: 1rem;
            border-radius: 50%;
            height: 35px;
            width: 35px;
            float: right;
        }

        .bg-red {
            background-color: #f03 !important;
        }

        .sub-header1 {
            width: 1170px;
            height: 50px;
        }

        .sub-header3 a {
            width: 124px;
            margin-left: 15px;
        }

        .sub-header3 {
            margin-left: 75px;
            margin-top: 70px;
        }

        .bs-example {
            width: 1170px;
            margin-left: 0;

        }

        .sider {
            min-height: calc(100vh - 60px);
            background: #ffffff;
            font-family: "Roboto", sans-serif;
            font-weight: 400;
            padding: 0;
            width: 257px;


            border-right: 2px solid #e3e3e3;
            border-bottom: 2px solid #e3e3e3;
        }

        .nav-item {
            border-bottom: 2px solid #e3e3e3;
            margin-top: 50px;
        }

        .text-white {
            color: #fff !important;
        }


	</style>





	<div class="sider" style="float: left">
		<ul class="nav">
			<li class="nav-item" style="margin-top: 1px">
				<a style="background-color:#000; " href="/main/"
				   class="list-group-item list-group-item-warning"><h3 class="text-white">Home</h3></a>
			</li>
			<li class="nav-item">
				<a style="background-color: #ff5916 !important; " href="/main1/" class="list-group-item list-group-item-warning">
					<h3 class="text-white">My own recipes</h3></a>
			</li>
			<li class="nav-item">
				<a style="background-color: #44c553 !important; " href="/meun/main/add/"
				   class="list-group-item list-group-item-success"><h3 class="text-white">Create recipe</h3></a>
			</li>
			<li class="nav-item">
				<a style="background-color: #7832e2 !important; " href="/meun/main/add1/"
				   class="list-group-item list-group-item-info"><h3 class="text-white">Customize recipe</h3></a>
			</li>
			<li class="nav-item">
				<a style="background-color: #35bdff !important; " href="/meun/main/add/"
				   class="list-group-item list-group-item-danger"><h3 class="text-white">Share recipes to friends</h3></a>
			</li>

			<li class="nav-item active">
				<a style="background-color: #ffde03 !important;" href="/meun/main/add/"
				   class="list-group-item list-group-item-primary"><h3 class="text-white">***</h3></a>
			</li>

		</ul>
	</div>




	<div class="container" style="margin-right: 0; margin-top: -20px; background-color: #f3f3f3">
		<div class="w clear">
			<div id="carousel-example-generic" style="width: 1170px; height: 500px;" class="carousel slide"
			     data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#carousel-example-generic" data-slide-to="0" class=""></li>
					<li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
					<li data-target="#carousel-example-generic" data-slide-to="2" class="active"></li>
				</ol>
				<div class="carousel-inner" style="width: 1170px; height: 500px;" role="listbox">
					<div style="width: 1170px; height: 500px;" class="item">
						<a href="/det_lun1/">
							<img style="width: 1170px; height: 500px;"
							     data-src="holder.js/1000x500/auto/#777:#555/text:First slide"
							     alt="First slide [1000x500]"
							     src="{% static 'img/gheymeh.jpeg' %}"
							     data-holder-rendered="true">
						</a>
					</div>
					<div class="item active left">
						<a href="/det_lun2/">
							<img style="width: 1170px; height: 500px;"
							     data-src="holder.js/900x500/auto/#666:#444/text:Second slide"
							     alt="Second slide [1000x500]"
							     src="{% static 'img/chicken-gyoza.jpeg' %}"
							     data-holder-rendered="true">
						</a>
					</div>
					<div class="item next left">
						<a href="/det_lun3/">
							<img style="width: 1170px; height: 500px;"
							     data-src="holder.js/1000x500/auto/#555:#333/text:Third slide"
							     alt="Third slide [1000x500]"
							     src="{% static 'img/Quesadilla.jpeg' %}"
							     data-holder-rendered="true">
						</a>
					</div>
				</div>
				<a class="left carousel-control" href="#carousel-example-generic" role="button"
				   data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#carousel-example-generic" role="button"
				   data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>

		</div>


		<div class="ad" style=" width: 1170px; height: 100px; margin-top: 110px; margin-left: -15px ">
			<img style="width: 1170px; height: 100px; " src="{% static 'img/img_5.png' %}">
		</div>
		<div class="ad" style=" width: 1170px; height: 100px; margin-left: -15px; margin-top: 10px; ">
			<img style="width: 1170px; height: 100px; " src="{% static 'img/img_6.png' %}">
		</div>
		<div class="sub-header1">
			<div class="sub-header">
				<a href="/subpage1/" target="_blank" title="一周最热">
					<img class="imgLoad" src="//static.meishichina.com/v6/img/zhen/r01.jpg" style="display: block;">
					Most popular
				</a>
				<a href="/subpage2/" target="_blank"
				   title="人气菜肴">
					<img class="imgLoad" src="//static.meishichina.com/v6/img/zhen/r02.jpg" style="display: block;">
					Best taste
				</a>
				<a href="/subpage3/" target="_blank" title="春季食谱">
					<img class="imgLoad" src="//static.meishichina.com/v6/img/zhen/cjsp.png"
					     style="display: block;">
					Vegetarianism
				</a>
				<a href="/subpage4/" target="_blank" title="高颜值">
					<img class="imgLoad" src="//static.meishichina.com/v6/img/zhen/r04.jpg" style="display: block;">
					Gorgeous
				</a>
				<a href="/subpage5/" target="_blank" title="快手菜">
					<img class="imgLoad" src="//static.meishichina.com/v6/img/zhen/r05.jpg" style="display: block;">
					Fast speed
				</a>
				<a href="/subpage6/" target="_blank" title="早餐">
					<img class="imgLoad" src="//static.meishichina.com/v6/img/zhen/r06.jpg" style="display: block;">
					Breakfast
				</a>
				<a href="/subpage7/" target="_blank" title="家常菜谱">
					<img class="imgLoad" src="//static.meishichina.com/v6/img/zhen/r07.jpg" style="display: block;">
					Homely recipes
				</a>
				<a href="/subpage8/" target="_blank" title="烘焙大全">
					<img class="imgLoad" src="//static.meishichina.com/v6/img/zhen/r08.jpg" style="display: block;">
					Baking
				</a>
				<a href="/subpage9/" target="_blank" title="亲子专区">
					<img class="imgLoad" src="//static.meishichina.com/v6/img/zhen/r09.jpg" style="display: block;">
					Children's food
				</a>
				<a href="/meun/list/" target="_blank" title="所有菜谱">
					<img class="imgLoad" src="//static.meishichina.com/v6/img/zhen/r10.jpg" style="display: block;">
					All menu
				</a>

			</div>
		</div>
		<div class="sub-header2">
			<div class="sub-header3">
				<a href="/meun/list/" target="_blank" class="btn btn-success"><h5>Recommend</h5></a>
				<a href="/subpage11/" target="_blank" class="btn btn-info"><h5>Staple Food</h5></a>
				<a href="/subpage12/" target="_blank" class="btn btn-warning"><h5>Dessert</h5></a>
				<a href="/subpage13/" target="_blank" class="btn btn-danger"><h5>Snack</h5></a>
				<a href="/subpage5/" target="_blank" class="btn btn-warning"><h5>Fast Food</h5></a>
				<a href="/subpage14/" target="_blank" class="btn btn-success"><h5>Western Food</h5></a>
				<a href="/category/list/" target="_blank" class="btn btn-info"><h5>All Categories</h5></a>
			</div>
		</div>

		<div class="bs-example" data-example-id="thumbnails-with-custom-content">
			<div class="row">
				<div class="row1">
					{% for obj in queryset %}
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<img style="width: 290px ;height:290px" src="/media/{{ obj.img }}"
								     data-src="holder.js/100%x200" alt="100%x200">
								<div class="caption" id="formAdd">
									<span class="avatar bg-red mr-3">
										<a id="btnSave" href="/meun/{{ obj.id }}/list/" style="color: white">
											<svg class="svg-inline--fa fa-heart fa-w-18"
											     style="width: 18px; height: 18px"
											     aria-hidden="true" data-prefix="fas"
											     data-icon="heart" role="img"
											     viewBox="0 0 576 512">

														<path fill="currentColor"
														      d="M414.9 24C361.8 24 312 65.7 288 89.3 264 65.7 214.2 24 161.1 24 70.3 24 16 76.9 16 165.5c0 72.6 66.8 133.3 69.2 135.4l187 180.8c8.8 8.5 22.8 8.5 31.6 0l186.7-180.2c2.7-2.7 69.5-63.5 69.5-136C560 76.9 505.7 24 414.9 24z">
														</path>
												</svg>
											</a>
									</span>
									<h2>{{ obj.name }}</h2>
									<h5>Category: {{ obj.get_cate_display }}</h5>
									<h5>Description: {{ obj.description }}</h5>
									<h5>Comment: {{ obj.get_rate_display }}</h5>
									<h5>Calories: {{ obj.calories }} kal</h5>


									<div style="float: right; margin-top: -50px">
										<form action="/meun/{{ obj.id }}/det/" method="POST">
											{% csrf_token %}
											<p>Quantity: <input type="text" name="tools"
											                    style="width: 40px; border: 2px solid greenyellow"
											                    value="{{ obj.quan }}"></p>

											<input style="width: 100px" class="btn btn-success" role="button"
											       type="submit" value="Start!!!"/>
										</form>

									</div>


								</div>

							</div>
						</div>
					{% endfor %}

				</div>
			</div>
			<ul class="pagination">
				{{ page_string }}
			</ul>
		</div>
	</div>

{% endblock %}
{% block js %}
	<script>
        $(function () {
            bindBtnSaveEvent();

        })

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                alert("Save Successfully in my favorite");


            });
        }


	</script>



{% endblock %}

app01/templates/personal.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
		.col-md-6 h2{
			padding-top: 40px;
		}

	</style>
	<div class="container">
		<div class="row" style="margin-left: 150px">
			<div class="col-md-6" style="border: 1px solid purple; width: 400px; height: 600px">
				<img style="height: 400px; width: 400px; padding-right: 20px" src="{% static 'img/111.jpeg' %}">
			</div>
			<div class="col-md-6" style="border: 1px solid purple; width: 400px; height: 600px; margin-left: 20px">
				<div>
					<h2>Email</h2>
				</div>
				<div>
					<h2>Email</h2>
				</div>
				<div>
					<h2>Email</h2>
				</div>
				<div>
					<h2>Email</h2>
				</div>
				<div>
					<h2>Email</h2>
				</div>




			</div>
		</div>


	</div>






{% endblock %}

app01/templates/subpage1.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
        .panel-body {
            padding: 5px;
        }

        .panel-body img {
            width: 160px;
            height: 160px;
        }

        .text {
            float: right;
            padding-right: 500px;
        }
	</style>
	<div class="container">
		{% for obj in queryset %}
			<h1 style="color: #985f0d">{{ obj.get_cate_display}}</h1>
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title"><h3>{{ obj.name }}</h3></h3>
				</div>
				<div class="panel-body">
					<img src="/media/{{ obj.img }}">
					<div class="text">
						<h3>Description：{{ obj.description }}</h3>
						<h3>Score：{{ obj.get_rate_display }}</h3>
					</div>

				</div>
			</div>
		{% endfor %}

	</div>



{% endblock %}

app01/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>

<div><p style=" "><a style=""
                                                   href="/meun/{{ obj.id }}/det/" class="btn btn-success"
                                                   role="button">Start!</a></p>
</div>

<div>
	<h5 style="   ">Quantity:<input
			style="width: 30px">
	</h5>
</div>
</body>
</html>